### ISSUE TITLE
Error 500 if Translation Overrides in Neos longer then 255 Characters

### ISSUE THREAD

**Issue by paavo** [sitegeist/Sitegeist.CsvPO#11]
If you try to add a TranslationOverride in Neos Backend who is longer than 255 Characters this will result in a `Doctrine\DBAL\Exception\DriverException` 💥 

```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'translation' at row 1
```

**Problem**: The field `translation` is defined as VARCHAR(255)

---

As limiting the translations to 255 chars in Neos Backend makes no sense to me i propose to extend the database field. 

Let's talk about your thoughts @mficzel and i'll create a PR ☝️

**Comment by paavo** [comment]
Thanks for merging 👍 
Don't forget to create a new release Tag  @mficzel  🙏

**Comment by mficzel** [comment]
Wait das ist ein irrtum da war ein typo im letzren release
